### ISSUE TITLE
Please add dependency of treq or txrequests

### ISSUE THREAD

**Issue by rvanlaar** [rockwelln/buildbot-slack#6]
Thanks for this plug and play buildbot plugin.

Could you add a line about installing either `treq` or `txrequests` in your readme?

I followed the installation steps and it wouldn't run.

I ended up with `treq`. That seems to be the most actively maintained of the two packages.

**Comment by rockwelln** [comment]
Thank you for your comment :-)
Did you try with the version 0.2.2?

The issue was raised in the ticket #5 and patched in setup.py (https://github.com/rockwelln/buildbot-slack/blob/8e420953c4f38ab2d1118c54837ec4d985181a17/setup.py#L19)

**Comment by rvanlaar** [comment]
Yes, I am using `0.2.2`. 
It seems the wheel that is on pypi does not contain the treq requirement.

Edit:
It seems I was too quick. Yes there is a requirement on treq. In that case I don't know what the problem was.

**Comment by rockwelln** [comment]
sorry, I mismatched keyword arguments of distutils and setuptools... :man_facepalming:
I'll merge the PR tomorrow and push a new version to PyPi

**Comment by rvanlaar** [comment]
Superb job.
Don't worry about the facepalm. It happens to us all. It evaded me as well, and I'm a long time python developer.
